"""Add user relationship to Donation

Revision ID: 3347d451b077
Revises: b6da423a2f90
Create Date: 2026-02-11 15:43:25.178755

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3347d451b077'
down_revision = 'b6da423a2f90'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
